include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_element: warning
    unused_import: warning
    dead_code: warning
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'

linter:
  rules:
    # Error prevention
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_print: false # Allow print for debugging
    avoid_renaming_method_parameters: true
    avoid_unused_constructor_parameters: true

    # Good practices
    always_use_package_imports: true
    camel_case_types: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Style
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    slash_for_doc_comments: true
